# Generated by Django 5.0 on 2025-09-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='multimedia',
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Audio file or podcast URL', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='flashcards',
            field=models.JSONField(blank=True, help_text="Store flashcards as JSON [{front:'word', back:'meaning'}]", null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo or hosted video URL', null=True),
        ),
    ]
